# Copyright 2011 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 27 Jan 2012, Modified by Julie Smith for Google Tasks Backup (tasks-backup), based on Google Tasks Porter

# ===== Production host and version ======
application: tasks-backup
version: 7

# ===== Limited Public Test host and version ======
#application: js-tasks
#version: 7

# ===== Private Alpha Test host and version ======
#application: js-tasks-test
#version: 7

# ===== 2nd Private Alpha Test host and version ======
#application: backup-tasks
#version: 7

# ===== Local host ==========
#application: tasks-backup-local
#version: 1

runtime: python
api_version: 1

# Static files remain cached by the browser for 12 hours
# default_expiration: "12h"


error_handlers:
  - file: error_handlers/error_default.html

  - error_code: over_quota
    file: error_handlers/error_over_quota.html
    
  - error_code: dos_api_denial
    file: error_handlers/error_dos.html
  
  - error_code: timeout
    file: error_handlers/error_timeout.html

    
handlers:
- url: /static
  static_dir: static
  secure: always
  

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico
  secure: always
  
- url: /info
  static_files: static/info.html
  upload: info.html
  secure: always
  
- url: /worker
  script: worker.py
  login: admin
  secure: always

- url: /admin/.*
  script: admin.py
  login: admin
  secure: always

# Main page does not require login, so that anyone can read main page before authorising
- url: /
  script: tasks_backup.py
  secure: always

# Subsequent pages require user to be logged in
- url: /.+
  script: tasks_backup.py
  login: required
  secure: always


# ============================
# For debug on localhost
# ============================
#- url: /oauth2callback
#  script: oauth2client/appengine.py
